name: build-and-push
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  build-and-push:
    name: Build all custom images and push them to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        image:
          - "nextcloud"
          - "vector-agent"
        tag:
          - "latest"
        include:
          - image: "nextcloud"
            tag: "27"
          - image: "vector-agent"
            tag: "0.41.X-alpine"
          - image: "vector-agent"
            tag: "latest-alpine"
    env:
      IMAGE_NAME: ${{ matrix.image }}
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
      DOCKER_TAG: ${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.DOCKER_TAG }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            DOCKER_TAG=${{ env.DOCKER_TAG }}
          context: ./${{ env.IMAGE_NAME }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
